# BEGIN_KITTY_THEME
include current-theme.conf # Catppuccin-Mocha
# END_KITTY_THEME

# font_family		Iosevka NFM Medium
# font_family		MesloLGS NF
# font_family		JetBrainsMono Nerd Font Mono
# font_family		JetBrainsMono NFM Medium
font_family		JetBrainsMono Nerd Font Propo
font_features JetBrainsMono Nerd Font Propo +liga +calt
disable_ligatures all never

font_size		18
bold_font		auto
italic_font		auto
bold_italic_font	auto

